name: LuckTags
version: '1.1'
main: dev.bauhd.lucktags.LuckTags
authors: [ BauHD ]
api-version: '1.21.7'
folia-supported: true

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
    MiniPlaceholders:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false